# Introducción a Jupyter notebooks y Pandas

*Nota*: Este texto es código Markdown, para saber más visita: https://www.markdownguide.org/basic-syntax/

Los jupyter notebook se componen de celdas, donde cada celda puede ser:
- Celda de código Python
- Celda de Markdown

### Markdown

Es un pseudo-código para formato de texto estándar y muy utilizado, permite un formato rápido y con la práctica nos permite crear documentos organizados. No tiene todas las opciones que un editor de texto completo (como Word) pero en la mayoría de casos es más que suficiente.

**Para activar el modo Markdown de una celda, utiliza el boton de tipo de celda en la barra superior de jupyter notebook**

Tips:

- En el modo navegación (celdas en color azul) puedes agregar una nueva celda con la tecla `a` 
- Para borrar celdas utilida doble 'd' es decir: `dd`

In [10]:
# Código Python
2+2

4

**Tip**
Ejecuta las celdas con `ctrl` + `enter`

In [16]:
2+2

4

# Arrays de Numpy

In [31]:
edad_alumnos = [30,26,40,35,28]
edad_alumnos

[30, 26, 40, 35, 28]

In [18]:
# Podemos duplicar la edad de cada alumno?
for e in edad_alumnos:
    print(e*2)

60
52
80
70
56

Numpy presenta la posibilidad de hacer operaciones vectoriales/ matriciales con Python

In [24]:
import numpy as np

edad_alumnos_array = np.array(edad_alumnos)

edad_alumnos_array

array([30, 26, 40, 35, 28])

In [25]:
edad_alumnos_array * 2

array([60, 52, 80, 70, 56])

# Pandas

### Series

Las series de Pandas son una innovación a los Array de Numpy, y agrega varios métodos muy comunes de Análisis de Datos y agrega indices editables para el usuario

In [26]:
import pandas as pd

In [27]:
# Lista de Python
edad_alumnos = [30,26,40,35,28]

In [28]:
# Array de Numpy
edad_alumnos_array = np.array([30,26,40,35,28])

In [29]:
# Serie de Pandas
edad_alumnos_serie = pd.Series([30,26,40,35,28])

In [37]:
edad_alumnos_serie * 2

0    60
1    52
2    80
3    70
4    56
dtype: int64

In [38]:
# Indice en listas

edad_alumnos[0]

30

In [39]:
edad_alumnos_serie[0]

30

In [46]:
edad_alumnos_serie = pd.Series([30,26,40,35,28], index=['a','b','c','d','e'])

In [44]:
edad_alumnos_serie

a    30
b    26
c    40
d    35
e    28
dtype: int64

In [49]:
edad_alumnos_serie > 30

a    False
b    False
c     True
d     True
e    False
dtype: bool

### Data Frames

Son tablas. Pero ojo: Cada columna es una serie de Pandas

In [50]:
nombres_alumnos = ['jose','ana','bruno','dafne','esli']

### Método 1 Para crear DataFrames

**Nota** Sí consideramos importante aprender los 2 métodos para crear data frames

###### Diccionario de listas

Es como pasar cada columna con su nombre de columna

In [59]:
pd.DataFrame({
    "edad": [30,26,40,35,28],
    "nombre" : ['jose','ana','bruno','dafne','esli']
})

   edad nombre
0    30   jose
1    26    ana
2    40  bruno
3    35  dafne
4    28   esli

### Método 2 Para crear DataFrames

##### Lista de Diccionarios

Es como pasar cada registro en forma de diccionario

In [62]:
pd.DataFrame([
    {"nombre":"jose", "edad": 30},
    {"nombre":"ana", "edad": 26},
    {"nombre":"bruno", "edad": 40}
])

  nombre  edad
0   jose    30
1    ana    26
2  bruno    40

## Actividad:
- Crea un data frame de una tienda (inventario) de 3 columnas: Nombre, Precio y ventas.
- Usando otro método de crear data frames, crea un data frame de alumnos: Nombre, Semestre, Promedio

In [64]:
tienda = pd.DataFrame([
    {"Nombre":"TV","Precio":2000,"Ventas":100},
    {"Nombre":"PC","Precio":20000,"Ventas":200},
    {"Nombre":"Celular","Precio":20000,"Ventas":50},
])

In [65]:
tienda

    Nombre  Precio  Ventas
0       TV    2000     100
1       PC   20000     200
2  Celular   20000      50

In [66]:
alumnos = pd.DataFrame({
    "nombre": ["Jose Manuel","Luis","Marialin"],
    "semestre": [4,6,8],
    "promedio": [8,9,10]
})

In [67]:
alumnos

        nombre  semestre  promedio
0  Jose Manuel         4         8
1         Luis         6         9
2     Marialin         8        10

# Filtrar un data frame - Crear subconjuntos

In [73]:
tienda

    Nombre  Precio  Ventas
0       TV    2000     100
1       PC   20000     200
2  Celular   20000      50

In [72]:
tienda[
    [True,False,True]
]

    Nombre  Precio  Ventas
0       TV    2000     100
2  Celular   20000      50

- Seleccionar la columna con la que vamos a hacer una operación lógica
- Guardar ese resultado
- Utilizarlo para filtrar

In [78]:
filtro = tienda["Ventas"] >= 100

In [80]:
filtro

0     True
1     True
2    False
Name: Ventas, dtype: bool

In [84]:
tienda_sub = tienda[filtro]

tienda_sub["Nombre"]

0    TV
1    PC
Name: Nombre, dtype: object

### Todo en un solo paso

In [87]:
tienda[tienda["Ventas"]>=100]["Nombre"]

0    TV
1    PC
Name: Nombre, dtype: object

# Loc & iLoc

In [88]:
tienda["Nombre"] # A los [] les puedo pasar un nombre de columna

0         TV
1         PC
2    Celular
Name: Nombre, dtype: object

In [89]:
tienda[tienda["Ventas"]>=100] # A los [] les puedo pasar un vector lógico (un filtro)

  Nombre  Precio  Ventas
0     TV    2000     100
1     PC   20000     200

### En los data frames, los [ ] son ambigüos

In [92]:
tienda

    Nombre  Precio  Ventas
0       TV    2000     100
1       PC   20000     200
2  Celular   20000      50

### Loc

Busqueda por "nombre"

In [93]:
# tienda.loc[ filas, columnas ]

# tienda.loc[0,"Nombre"]

tienda.loc[0,:]

Nombre      TV
Precio    2000
Ventas     100
Name: 0, dtype: object

In [95]:
# tienda.loc[:,0] # Esto produce error porque necesita el nombre de la columna

### iLoc

Busqueda por posición

In [102]:
tienda.iloc[:,1]

0     2000
1    20000
2    20000
Name: Precio, dtype: int64

In [104]:
tienda[tienda["Ventas"]>=100].iloc[:,0]

0    TV
1    PC
Name: Nombre, dtype: object

In [106]:
# tienda[tienda.iloc[:,2]>=100].iloc[:,0]

filtro_ventas_mayores_100 = tienda.iloc[:,2]>=100

tiendas_mayores_a_100 = tienda[filtro_ventas_mayores_100]

nombre_tiendas_mayores_a_100 = tiendas_mayores_a_100.iloc[:,0]

In [107]:
nombre_tiendas_mayores_a_100

0    TV
1    PC
Name: Nombre, dtype: object

# Lectura de archivos CSV

In [116]:
titanic = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/raw/titanic.csv")

In [110]:
titanic

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Cuál es la distribución de embarked entre hombres y mujeres ?

In [117]:
titanic["embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

# CUIDADO

Al hacer test de "igual a..." no cometer el error de "asignar"

` titanic["sex"] = "male"`

Este código está sobreescribiendo a todos los registros / filas del dataset para ser iguales a "male"

## Método .value_counts()

In [121]:
# Filtro por todos los registros donde sex = male, selecciono la columna "embarked" ,
# finalmente uso el mètodo value_counts()

titanic[titanic["sex"] == "male"]["embarked"].value_counts()

S    441
C     95
Q     41
Name: embarked, dtype: int64

In [122]:

titanic[titanic["sex"] == "female"]["embarked"].value_counts()

S    203
C     73
Q     36
Name: embarked, dtype: int64