### Tips de navegación con Jupyter Notebook

- Recuerda que las celdas tienen modo de navegación- azul y edición - verde
- Con "a" en modo de navegación agregamos una celda arriba
- Con "b" en modo de navegación agregamos una celda debajo
- Con "m" cambiamos el modo de la celda a Markdown
- Con "y" cambiamos el modo de la celda a código

In [1]:
import pandas as pd

In [3]:
pd.Series([1])

0    1
dtype: int64

### Cargar datos

https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [4]:
pwd

'/Users/josemanuelbarrera/Documents/202509-Data-Analytics-con-Python/Live Coding/Clase 05'

In [108]:
titanic = pd.read_csv("../../data/titanic.csv", sep=",")

In [109]:
titanic

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Método: value_counts()

https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html

In [9]:
titanic["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

### Seleccionar más de una columna en un data frame

In [11]:
df = pd.DataFrame({
    "model": ["A1", "A3", "A4"],
    "price": [12000, 15000, 18000],
    "year": [2018, 2019, 2020]
})

In [21]:
columnas = ["model","price"]

# sub = df[columnas]

sub = df[["model","price"]]

In [19]:
df

  model  price  year
0    A1  12000  2018
1    A3  15000  2019
2    A4  18000  2020

In [20]:
sub

  model  price
0    A1  12000
1    A3  15000
2    A4  18000

In [28]:
# Nota: Es posible seleccionar columnas para "descartar" utilizando el método .drop
df.drop(columns=columnas)

   year
0  2018
1  2019
2  2020

### Selecciona más de una columna del Data Frame en Titanic

In [32]:
titanic[["sex","survived"]]

        sex  survived
0      male         0
1    female         1
2    female         1
3    female         1
4      male         0
..      ...       ...
886    male         0
887  female         1
888  female         0
889    male         1
890    male         0

[891 rows x 2 columns]

### Loc & iLoc

- **Loc** busqueda por nombre
- **iLoc** busqueda por posición

In [34]:
df[df["price"]<=15000]

  model  price  year
0    A1  12000  2018
1    A3  15000  2019

In [38]:
# loc[filas, columnas]
# loc[filas donde precio sea menor o igual a 15K, columnas iguales a model, price]
df.loc[df["price"]<=15000,["model","price"]]

  model  price
0    A1  12000
1    A3  15000

In [41]:
df.iloc[[0,2],[0,1]]

  model  price
0    A1  12000
2    A4  18000

### Con todo lo anterior...
### Cuántos hombres sobrevivieron al Titanic ? Y cuántas mujeres sobrevivieron al titanic ?

In [48]:
titanic.loc[titanic["sex"]=="male","survived"].value_counts()

0    468
1    109
Name: survived, dtype: int64

In [49]:
titanic.loc[titanic["sex"]=="female","survived"].value_counts()

1    233
0     81
Name: survived, dtype: int64

In [63]:
titanic.loc[(titanic["sex"]=="male") & (titanic["survived"]==1),"survived"].count()

109

In [69]:
# Encadenamiento de métodos
titanic.loc[titanic["sex"]=="male"].loc[titanic["survived"]==1]["survived"].count()

109

# Valores ausentes, valores perdidos, valores NA, valores faltantes, missing values

In [72]:
titanic["sex"].value_counts(dropna=False)

male      577
female    314
Name: sex, dtype: int64

# .info()

Nos da información general, y muy útil, sobre nuestro data frame

In [74]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   name      891 non-null    object
 3   sex       891 non-null    object
 4   age       714 non-null    float64
 5   sibsp     891 non-null    int64
 6   parch     891 non-null    int64
 7   ticket    891 non-null    object
 8   fare      891 non-null    float64
 9   cabin     204 non-null    object
 10  embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

In [80]:
# Por qué los strings aparecen como objeto ? 

pd.Series(["a","b","c",1,2,[9,0]]) # Esto es nada recomendado, tratemos de evitarlo

0         a
1         b
2         c
3         1
4         2
5    [9, 0]
dtype: object

# Valores Ausentes

Tenemos opciones al encontrar valores ausentes:
- Eliminarlos
- Analizarlos
- Imputarlos

Encontrar valores ausentes requiere métodos especiales

In [92]:
# Esto no sirve
# titanic["age"] == pd.np.nan

https://pandas.pydata.org/docs/reference/api/pandas.Series.isna.html

In [94]:
titanic["age"].isna()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: age, Length: 891, dtype: bool

In [95]:
titanic["age"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: age, Length: 891, dtype: bool

## Cómo seleccionar los  NA ?

In [98]:
titanic_missing_age = titanic[titanic["age"].isna()]
titanic_missing_age

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Exportar a CSV

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv

In [99]:
titanic_missing_age.to_csv("missing_rows.csv")

In [103]:
titanic_missing_age.to_csv("missing_rows.csv", sep="|")

### Exportar a Excel

In [100]:
titanic_missing_age.to_excel("missing_rows.xlsx")

In [ ]:
titanic_missing_age.to

# Cómo filtrar (drop) las filas con NA ?

In [114]:
# El caracter de "~" invierte el sentido de una serie booleana ( lógica )
~titanic["age"].isna()

0       True
1       True
2       True
3       True
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: age, Length: 891, dtype: bool

In [115]:
titanic_valid_age = titanic[~titanic["age"].isna()]
titanic_valid_age

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [116]:
titanic_valid_age.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  714 non-null    int64
 1   pclass    714 non-null    int64
 2   name      714 non-null    object
 3   sex       714 non-null    object
 4   age       714 non-null    float64
 5   sibsp     714 non-null    int64
 6   parch     714 non-null    int64
 7   ticket    714 non-null    object
 8   fare      714 non-null    float64
 9   cabin     185 non-null    object
 10  embarked  712 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 66.9+ KB

# Seleccionar toda la data válida

En ciencia de datos, en la parte de modelado de datos. Para eso existe un método que "tira" todos los datos que presenten algún valor ausente. En otras palabras, retiene sólo "datos validos"

In [123]:
titanic_valid_values = titanic.dropna()

titanic_valid_values

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [118]:
titanic.dropna(axis=1)

,survived,pclass,name,sex,sibsp,parch,ticket,fare
0,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

# Imputar valores ausentes

**Nota**: Imputar significa estimar, aqui debemos recordar que vamos a introducir un margen de error derivado de nuestra imputación.

In [130]:
# Sobre escribe los valores NA
titanic["age_imputed"] = titanic["age"].fillna(round(titanic["age"].mean(),0))

In [131]:
titanic

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,age_imputed
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,27.0
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,19.0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,30.0
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,26.0
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,32.0